### ISSUE TITLE
Remove Three Widgets: AVG CANCELS, WINBACKS, and CANCELS BY PLATFORM

### ISSUE THREAD

**Issue by andrewgrosso** [andrewgrosso/dashboard#1]
Let's hide these three widgets from the production instance:
AVG CANCELS, WINBACKS, and CANCELS BY PLATFORM
Screenshot of them: http://screencast.com/t/LBg7EeYp5iiQ

**Acceptance Criteria:**

- User views the page.
- Those widgets aren't there. 
- The Marketing section is brought up higher.

**Comment by klapouchy** [comment]
Done!
