### ISSUE TITLE
TEXT CHANGE: Update Subtext Labels for Subscribers section

### ISSUE THREAD

**Issue by andrewgrosso** [andrewgrosso/dashboard#10]
1. Underneath TOTAL PAYING SUBS, remove the subtext.
2. Under TOTAL SUBSCRIBERS change this:
_Predicted at 42,000_
to this:
_Excludes Pending Cancellations_ 
3. Underneath TOTAL TRIAL USERS, remove the subtext

**Comment by klapouchy** [comment]
Done!
