### ISSUE TITLE
Remove Widget: Pie Chart for Registrations by Platform

### ISSUE THREAD

**Issue by andrewgrosso** [andrewgrosso/dashboard#3]
Cut this section:
http://screencast.com/t/Z4nV8PT5

**Acceptance Criteria:**
The other widgets swing over so there isn't a giant gaping hole - a small gaping hole is fine.
http://screencast.com/t/RxDV8CL7cd
Keep the mapping criteria - we'll need it for other widgets.

**Comment by klapouchy** [comment]
Done!

<img width="1233" alt="screen shot 2016-10-03 at 1 29 12 pm" src="https://cloud.githubusercontent.com/assets/136622/19035992/6d5d2946-896d-11e6-8659-00f3bc8cdba5.png">
